image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Android SDK
    init: bash gitpod-setup.sh
    command: echo "Android SDK Ready"

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - ms-azuretools.vscode-docker
